//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiTao.Modules.Bll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int CollertionId { get; set; }
        public int AccountId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int ShangPinId { get; set; }
        public int Type { get; set; }
    }
}
