//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiTao.Modules.Bll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DingDan
    {
        public int DingDanId { get; set; }
        public double Price { get; set; }
        public string ShangPinName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int AccountId { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public int Description { get; set; }
        public int ShangPinCount { get; set; }
    }
}
