//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiTao.Modules.Bll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShangPin
    {
        public int ShangPinId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string YuanPrice { get; set; }
        public Nullable<int> MonthlySales { get; set; }
        public Nullable<int> CollectCount { get; set; }
        public string Url { get; set; }
        public string TransportationPrice { get; set; }
        public string ToWhere { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> XiaoLeiId { get; set; }
        public Nullable<int> FanJiFen { get; set; }
        public Nullable<int> BaoYou { get; set; }
    }
}
